name: helloworld
description: Dart gRPC sample client and server.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  grpc:
    path: ../grpc
  archive: ^3.0.0

  async: ^2.5.0
  crypto: ^3.0.0
  fixnum: ^1.0.0
  googleapis_auth: ^1.0.0
  meta: ^1.3.0
  http: ^0.13.0
  http2: ^2.0.0
  protobuf: ^2.0.0
